Repository Challenge-Closure/Garlic-Toast, pull requests merged in 2024-10, with the labels that each got.

#8 [Docs] Readme CONTRIBUTING 링크 수정
  README.md
Labels: 문서 수정

#15 [Docs]: Readme issue 연결 수정, contributer 추가, 메인 이미지크기 조정
  README.md
Labels: 문서 수정

#9 [Docs] contributing.md url 수정
  .github/CONTRIBUTING.md
  README.md
Labels: 문서 수정

#1 refactor: create new Types for EventBus
  src/types/EventType.ts
  src/utils/eventBus.ts
Labels: 리팩토링

#16 [Realease] npm 자동 배포 1차시도
  .github/workflows/package-deploy-release.yml
Labels: 기능 개발

#25 docs: readme 배포링크 수정
  README.md
Labels: 문서 수정
